services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-platform-postgres
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - booking_postgres_data:/var/lib/postgresql/data

volumes:
  booking_postgres_data: